// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ExtrapagesDocumentDataSlicesSlice = MissonSlice | AboutSlice;

/**
 * Content for extrapages documents
 */
interface ExtrapagesDocumentData {
  /**
   * Slice Zone field in *extrapages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: extrapages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExtrapagesDocumentDataSlicesSlice> /**
   * Meta Title field in *extrapages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: extrapages.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *extrapages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: extrapages.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *extrapages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: extrapages.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * extrapages document from Prismic
 *
 * - **API ID**: `extrapages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExtrapagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExtrapagesDocumentData>,
    "extrapages",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | EnquirySlice
  | HomeservicesSlice
  | WhyusSlice
  | HeroSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * OG image field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
   * Meta Title field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ExtrapagesDocument
  | HomeDocument
  | SettingsDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * header field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * writeup1 field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.writeup1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup1: prismic.KeyTextField;

  /**
   * writupe2 field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.writupe2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writupe2: prismic.KeyTextField;

  /**
   * writeup3 field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.writeup3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup3: prismic.KeyTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Enquiry → Default → Primary*
 */
export interface EnquirySliceDefaultPrimary {
  /**
   * writeup field in *Enquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: enquiry.default.primary.writeup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup: prismic.KeyTextField;

  /**
   * header field in *Enquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: enquiry.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;
}

/**
 * Default variation for Enquiry Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EnquirySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EnquirySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Enquiry*
 */
type EnquirySliceVariation = EnquirySliceDefault;

/**
 * Enquiry Shared Slice
 *
 * - **API ID**: `enquiry`
 * - **Description**: Enquiry
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EnquirySlice = prismic.SharedSlice<
  "enquiry",
  EnquirySliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * header1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.header1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header1: prismic.KeyTextField;

  /**
   * header2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.header2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header2: prismic.KeyTextField;

  /**
   * products button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Check Our Products
   * - **API ID Path**: hero.default.primary.products_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  products_button: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Homeservices → Default → Primary → services container*
 */
export interface HomeservicesSliceDefaultPrimaryServicesContainerItem {
  /**
   * service image field in *Homeservices → Default → Primary → services container*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homeservices.default.primary.services_container[].service_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_image: prismic.ImageField<never>;

  /**
   * service header1 field in *Homeservices → Default → Primary → services container*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homeservices.default.primary.services_container[].service_header1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_header1: prismic.KeyTextField;

  /**
   * service header2 field in *Homeservices → Default → Primary → services container*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homeservices.default.primary.services_container[].service_header2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_header2: prismic.KeyTextField;

  /**
   * service writeup field in *Homeservices → Default → Primary → services container*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homeservices.default.primary.services_container[].service_writeup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_writeup: prismic.KeyTextField;
}

/**
 * Primary content in *Homeservices → Default → Primary*
 */
export interface HomeservicesSliceDefaultPrimary {
  /**
   * header field in *Homeservices → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homeservices.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * services container field in *Homeservices → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homeservices.default.primary.services_container[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services_container: prismic.GroupField<
    Simplify<HomeservicesSliceDefaultPrimaryServicesContainerItem>
  >;
}

/**
 * Default variation for Homeservices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeservicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeservicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Homeservices*
 */
type HomeservicesSliceVariation = HomeservicesSliceDefault;

/**
 * Homeservices Shared Slice
 *
 * - **API ID**: `homeservices`
 * - **Description**: Homeservices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeservicesSlice = prismic.SharedSlice<
  "homeservices",
  HomeservicesSliceVariation
>;

/**
 * Primary content in *Misson → Default → Primary*
 */
export interface MissonSliceDefaultPrimary {
  /**
   * header field in *Misson → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: misson.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * writeup1 field in *Misson → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: misson.default.primary.writeup1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup1: prismic.KeyTextField;

  /**
   * writeup2 field in *Misson → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: misson.default.primary.writeup2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup2: prismic.KeyTextField;

  /**
   * writeup3 field in *Misson → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: misson.default.primary.writeup3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup3: prismic.KeyTextField;
}

/**
 * Default variation for Misson Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MissonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Misson*
 */
type MissonSliceVariation = MissonSliceDefault;

/**
 * Misson Shared Slice
 *
 * - **API ID**: `misson`
 * - **Description**: Misson
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissonSlice = prismic.SharedSlice<"misson", MissonSliceVariation>;

/**
 * Primary content in *Whyus → Default → Primary*
 */
export interface WhyusSliceDefaultPrimary {
  /**
   * Header field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Writeup1 field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.writeup1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup1: prismic.KeyTextField;

  /**
   * Writeup2 field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.writeup2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup2: prismic.KeyTextField;

  /**
   * Writeup3 field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.writeup3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup3: prismic.KeyTextField;

  /**
   * Writeup4 field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.writeup4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup4: prismic.KeyTextField;

  /**
   * Writeup5 field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.writeup5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup5: prismic.KeyTextField;
}

/**
 * Default variation for Whyus Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyusSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyusSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Whyus*
 */
type WhyusSliceVariation = WhyusSliceDefault;

/**
 * Whyus Shared Slice
 *
 * - **API ID**: `whyus`
 * - **Description**: Whyus
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyusSlice = prismic.SharedSlice<"whyus", WhyusSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ExtrapagesDocument,
      ExtrapagesDocumentData,
      ExtrapagesDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      EnquirySlice,
      EnquirySliceDefaultPrimary,
      EnquirySliceVariation,
      EnquirySliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HomeservicesSlice,
      HomeservicesSliceDefaultPrimaryServicesContainerItem,
      HomeservicesSliceDefaultPrimary,
      HomeservicesSliceVariation,
      HomeservicesSliceDefault,
      MissonSlice,
      MissonSliceDefaultPrimary,
      MissonSliceVariation,
      MissonSliceDefault,
      WhyusSlice,
      WhyusSliceDefaultPrimary,
      WhyusSliceVariation,
      WhyusSliceDefault,
    };
  }
}
